import re

def format_summary(text):
    # Strip markdown bold markers and leading whitespace/hashes from the text
    cleaned = re.sub(r'\*\*', '', text)
    cleaned = re.sub(r'^#+\s*', '', cleaned, flags=re.MULTILINE)

    # Extract title and summary using flexible regex
    title_match = re.search(r'Title:\s*(.+)', cleaned)
    summary_match = re.search(r'Summary:\s*(.+)', cleaned, re.DOTALL)

    parts = []
    if title_match:
        parts.append(f'<b>{title_match.group(1).strip()}</b>')
    if summary_match:
        parts.append(summary_match.group(1).strip())

    # Fallback: if parsing failed entirely, just return the raw text
    return '\n\n'.join(parts) if parts else text


def create_html_newsletter(summary_hn, summary_lobsters, hn_stories, lobsters_stories):
    # Apply formatting to summaries
    summary_hn_html = f"<div class='summary'><h2>Hacker News Top Story Summary</h2><p>{format_summary(summary_hn)}</p></div>"
    summary_lobsters_html = f"<div class='summary'><h2>Lobsters Top Story Summary</h2><p>{format_summary(summary_lobsters)}</p></div>"
    
    # Generate HTML for story links (remains unchanged)
    hn_links_html = '<ol>' + ''.join(f'<li><a href="{story["url"]}" class="story-link">{story["title"]}</a></li>' for story in hn_stories) + '</ol>'
    lobsters_links_html = '<ol>' + ''.join(f'<li><a href="{story["url"]}" class="story-link">{story["title"]}</a></li>' for story in lobsters_stories) + '</ol>'

    # Define footer HTML (remains unchanged)
    footer_html = """<footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc;"><p style="font-size: 14px; color: #666;">Disclaimer: All summaries were generated by AI. Hallucinations and formatting inconsistencies may occur.</p></footer>"""

    # Combine all HTML sections (remains unchanged)
    newsletter_html = f"""<!DOCTYPE html><html><head><style>body {{ font-family: Arial, sans-serif; }}.exec-summary, .story-section, footer {{ margin-bottom: 20px; }}.story-header {{ font-size: 20px; color: #333; }}.story-link {{ text-decoration: none; color: #007bff; }}ol {{ padding-left: 20px; }}h2 {{ color: #333; }}p, footer p {{ margin: 10px 0; font-size: 16px; }}footer {{ font-size: 14px; color: #666; text-align: center; }}</style></head><body>{summary_hn_html}{summary_lobsters_html}<div class="story-section"><h2 class="story-header">Top Hacker News Stories</h2>{hn_links_html}</div><div class="story-section"><h2 class="story-header">Top Lobsters Stories</h2>{lobsters_links_html}</div>{footer_html}</body></html>"""

    return newsletter_html

